Hollieatron/grace-shopper

server/db/models/index.js, server/db/models/reviews.js
=> create review model

package-lock.json, server/db/models/category.js, server/db/models/manufacturer.js, server/db/models/seller.js, server/db/models/user.js
Created User, Manufacturer, Seller, Category models.
Closes #10 
Closes #6
=> Eliot models

server/db/models/products.js
completed products model
closes #8 #13
=> finished model

server/db/models/seller.js, server/db/models/user.js
Updates to User Model & seller model to correctly include isAdmin boolean and correct Seller table name.
=> Minorupdates

server/db/models/index.js, server/db/models/product.js
=> Fix product relationship

client/components/index.js, client/components/product-form.js, client/routes.js, client/store/index.js, client/store/product.js, client/store/products.js, package-lock.json, package.json, server/api/index.js, server/api/products.js
#26 
- create productForm component w/ basic error handling
**add products**
- can add product to database successfully + updates redux store
- renders at "/admin/products/add" and is available to all visitors because admin access isn't set up yet
- currently redirects to "/products/product/:id" because we don't have a single view yet
**edit products**
- can edit product in database successfully + updates redux store
- renders at "/admin/products/edit/:id" and is available to all visitors because admin access isn't set up yet
- TO DO: prepopulate form with data! currently input remains blank
- currently redirects to "/products/product/:id" because we don't have a single view yet
=> Can add & edit products

client/store/product-reducers/product.js, server/api/admin/index.js
=> Fix admin routes

script/seed.js, script/seedData.js
=> updated seed file to include more items

client/components/categories/category-card.js, client/components/categories/category-grid.js, client/components/home.js, client/components/index.js, client/store/category-reducers/index.js, client/store/index.js, server/db/models/category.js
=> Category grid

client/components/navbar/category-list.js, client/components/navbar/navbar.js, client/components/products/category-dropdown.js, client/components/products/product-catalog.js, client/components/products/product-form.js, client/components/products/single-product-page.js
=> Admin func

script/seed.js
close #62 no robot names yet but fixed deadlock issue and products having all categories
=> fixed seedfile for deadlock

client/components/products/product-grid.js, server/api/products/index.js
=> No products

client/components/products/empty-product.js, client/components/products/product-grid.js
quick update to move no products into separate component
=> moved no products into separate component

client/components/products/product-catalog.js, script/seedData.js, server/db/models/product.js
=> added inventory and robots deadlock error persists

client/components/products/category-checkbox.js, client/components/products/product-catalog.js, client/components/products/product-form.js, client/store/product-reducers/product.js, server/api/admin/index.js, server/api/products/index.js, server/db/db.js
=> Update edit form

client/components/navbar/category-list.js, client/components/products/product-catalog.js, client/components/products/single-product-page.js
=> buttons updated

client/components/products/category-checkbox.js, client/components/products/product-form.js, server/api/admin/index.js, server/api/categories/index.js, server/api/products/index.js
=> Prepopulate edit form

client/components/products/product-form.js, client/routes.js, script/seed.js, server/api/admin/index.js, server/api/index.js
=> front and back end protection completed

client/components/products/product-form.js, client/components/reviews/review-page.js, client/routes.js, server/api/index.js
=> bugs fixed

client/components/categories/category-form.js, client/components/products/product-catalog.js, client/components/products/product-grid.js, client/routes.js
=> fixed bugs

server/api/reviews.spec.js, server/db/models/review.spec.js
=> Add tests for review route + model

script/seed.js, script/seedData.js, script/test-seed.js, server/api/cart/index.js, server/api/index.js, server/api/products/index.js, server/api/products/products.spec.js, server/db/models/cart.js, server/db/models/cartinventory.js, server/db/models/index.js
Updates cart model to have inventory at the cart/inventory/product level.
=> Cart model update

client/components/navbar/navbar.js, client/components/users/auth-form.js
=> Style login/signup form

client/components/orderhistory/order-history-item.js, client/components/orderhistory/order-item.js, client/components/orderhistory/user-order-history.js, client/store/order-reducers/user-order-history.js
=> Create order history

client/components/cart/cart-item.js, client/store/cart-reducers/index.js, server/api/cart/index.js
=> Delete product from cart

client/router/admin-routes.js, server/api/admin/admin.spec.js, server/api/products/products.spec.js
Adds the order history route to the administrator page as well as the user page
=> route added

client/components/cart/cart-item.js, client/components/products/single-product-page.js
Update add to cart so you can't add more than the available inventory of a product
=> Fix add to cart

client/components/orderhistory/order-management-item.js, client/components/orderhistory/order-management.js, client/components/orderhistory/user-order-history.js, client/store/order-reducers/order-history.js, server/api/admin/index.js, server/api/index.js, server/api/orderhistory/index.js
=> Update order history

client/components/cart/cart-page.js, client/components/navbar/navbar.js, client/components/products/product-card.js, client/components/products/product-grid.js, client/store/cart-reducers/index.js, client/store/index.js, client/store/user-reducers/user.js, server/api/cart/index.js, server/auth/index.js
Add add product button to product cards
=> Guest cart
